version: '3'
services:
  web:
    image: axayp/express-social:1.0 #we already have deployed the image to docker-hub so using it directly | Dockerfile in current directory is something that we have pushed to docker-hub as an image
    build:
      context: .
      dockerfile: /bin/true  # Use a no-op command as the Dockerfile
    ports:
      - "3000:3000"
  db:
    image: mongo:latest
